baseURL = "https://blog.victorbersy.com"
languageCode = "en-us"
title = "Blog de Victor Bersy"
theme = "ananke"

DefaultContentLanguage = "en"

[params]
  twitter = "https://twitter.com/victorbersy"
  github = "https://github.com/victorbersy"
  linkedin = "https://linkedin.com/in/victor-bersy"
  featured_image = "/bg.jpg"
  show_reading_time = true
